export const MAP = [
  ['1', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2'],
  ['|', '.', '.', '.', '.', '.', '.', '.', '.', '.', '|'],
  ['|', '.', 'b', '.', '[', '7', ']', '.', 'b', '.', '|'],
  ['|', '.', '.', '.', '.', '_', '.', '.', '.', '.', '|'],
  ['|', '.', '[', ']', '.', '.', '.', '[', ']', '.', '|'],
  ['|', '.', '.', '.', '.', '^', '.', '.', '.', '.', '|'],
  ['|', '.', 'b', '.', '[', '+', ']', '.', 'b', '.', '|'],
  ['|', '.', '.', '.', '.', '_', '.', '.', '.', '.', '|'],
  ['|', '.', '[', ']', '.', '.', '.', '[', ']', '.', '|'],
  ['|', '.', '.', '.', '.', '^', '.', '.', '.', '.', '|'],
  ['|', '.', 'b', '.', '[', '5', ']', '.', 'b', '.', '|'],
  ['|', '.', '.', '.', '.', '.', '.', '.', '.', 'p', '|'],
  ['4', '-', '-', '-', '-', '-', '-', '-', '-', '-', '3'],
];

export const IMAGE_PATHS_MAP = {
  '-': './assets/pipeHorizontal.png',
  '|': './assets/pipeVertical.png',
  '1': './assets/pipeCorner1.png',
  '2': './assets/pipeCorner2.png',
  '3': './assets/pipeCorner3.png',
  '4': './assets/pipeCorner4.png',
  'b': './assets/block.png',
  '[': './assets/capLeft.png',
  ']': './assets/capRight.png',
  '_': './assets/capBottom.png',
  '^': './assets/capTop.png',
  '+': './assets/pipeCross.png',
  '5': './assets/pipeConnectorTop.png',
  '6': './assets/pipeConnectorRight.png',
  '7': './assets/pipeConnectorBottom.png',
  '8': './assets/pipeConnectorLeft.png',
};
